# .github/workflows/build.yml
name: Build Gauguin SukiSU‑Ultra Kernel

# 手动触发
on:
  workflow_dispatch:

jobs:
  build:
    name: Compile SukiSU-Ultra Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc kmod libssl-dev flex bison python3 python3-distutils

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max_size: '10G'

      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Setup AOSP Clang
        run: |
          wget -qO clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/clang-r416183b.tar.gz
          tar xf clang.tar.gz
          echo "export PATH=$PWD/clang-r416183b/bin:\$PATH" >> $GITHUB_ENV

      - name: Apply SUSFS & KernelSU patches
        run: |
          git clone --depth=1 https://github.com/ShirkNeko/SukiSU-Ultra.git -b susfs-stable susfs
          git clone --depth=1 https://github.com/tiann/KernelSU.git KernelSU
          cd susfs && bash apply_patch.sh ../ && cd ..
          cd KernelSU && bash apply_patches.sh ../ && cd ..

      - name: Configure defconfig
        run: make vendor/gauguin_user_defconfig

      - name: Build kernel
        run: |
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy

      - name: Prepare AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AnyKernel3
          cp arch/arm64/boot/Image.gz-dtb AnyKernel3
          cd AnyKernel3 && zip -r ../SukiSU-gauguin.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: SukiSU-Ultra-gauguin
          path: SukiSU-gauguin.zip
